# This file is an example to demonstrate the usage of DSM CLI inside a GitHub pipeline
# Make sure to upload the executable and the configuration files to your project
# For more information on its usage, please visit https://docs.senhasegura.io/

name: senhasegura® CLI CI/CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run DSM CLI as Running Belt
        env:
          SENHASEGURA_CLIENT_ID: ${{ secrets.SENHASEGURA_CLIENT_ID }}
          SENHASEGURA_CLIENT_SECRET: ${{ secrets.SENHASEGURA_CLIENT_SECRET }}
          SENHASEGURA_URL: ${{ secrets.SENHASEGURA_URL }}
          MAPPING_TEST: ${{ secrets.MAPPING_TEST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY_VARIABLE: ${{ secrets.AWS_SECRET_ACCESS_KEY_VARIABLE }}
          AZURE_ACCESS_KEY_ID_VARIABLE: ${{ secrets.AZURE_ACCESS_KEY_ID_VARIABLE }}
          AZURE_SECRET_ACCESS_KEY_VARIABLE: ${{ secrets.AZURE_SECRET_ACCESS_KEY_VARIABLE }}
          DATABASE_IP: ${{ secrets.DATABASE_IP }}
          GCP_ACCESS_KEY_ID_VARIABLE: ${{ secrets.GCP_ACCESS_KEY_ID_VARIABLE }}
          GCP_SECRET_ACCESS_KEY_VARIABLE: ${{ secrets.GCP_SECRET_ACCESS_KEY_VARIABLE }}
          SENHASEGURA_MAPPING_FILE: ${{ secrets.SENHASEGURA_MAPPING_FILE }}
        run: |
          chmod +x dsm
          ./dsm runb \
            --application "Git Hub" \
            --system "Lab" \
            --environment "Lab" \
            --tool github \
            -v \
          source .runb.vars && rm .runb.vars

